 spring
profiles:
 active:test
---
spring 
 profiles:
 active:test
application:
name :tulinvip05-ms-test
server:
port:8080
---
spring 
 profiles:
 active:prod
application:
name :tulinvip05-ms-prod
server:
port:8088